name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Message that will be displayed on users''Hello @${{ github.actor }} ,thank you submitting issue!'
        pr-message: 'Message that will be displayed on users''Hello @${{ github.actor }} ,thank you submitting a pull request!'
